[package]
name = "express-vpn-gui"
version = "0.1.0"
authors = ["kunicmarko20 <kunicmarko20@gmail.com>"]
edition = "2018"

[dependencies]
arc-guard = "0.2.0"
clap = "2.32.0"
dirs = "1.0.4"
glib = "0.10.3"
gtk = "0.9.2"
libappindicator = "0.5.0"
libc = "0.2.49"
structopt = "0.2.13"
